name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
    - name: Test
      working-directory: ./rust
      run: cargo test --verbose
